name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get build version
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')${{github.run_number}}"
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      working-directory: ./src/ZonyLrcTools.Cli
      run: |
        ls -a
        chmod +x ./publish.sh
        ./publish.sh
      shell: bash
      env:
        VERSION: ${{ steps.date.outputs.date }}
    - name: ls
      run: ls -a
    # - name: Upload Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "*.zip"
    #     token: ${{ secrets.GITHUBACTIONS }}
    #     tag: ZonyLrcToolsX_Alpha.${{ steps.date.outputs.date }}
    #     commit: dev